### ISSUE TITLE
Long `code` lines overflow the container and stretch the viewport

### ISSUE THREAD

**Issue by adborden** [18F/swagger-ui#10]
The docs from [schedule_a](https://api.open.fec.gov/developers/#!/schedules/schedule_a) for example stretches out the viewport.
![screenshot from 2016-06-24 16-46-08](https://cloud.githubusercontent.com/assets/509703/16353562/0ef2ad62-3a31-11e6-806f-8a2bf03364c0.png)

**Comment by adborden** [comment]
I think [this should fix it](https://github.com/18F/swagger-ui/compare/master...18F:bug/scroll-code), but having trouble running the tests, `jshint` doesn't seem to be configured properly. I'll pick this back up Monday, but leaving it here in case someone wants to pick it up.

**Comment by adborden** [comment]
Doh, it should be `overflow-x: auto`.

**Comment by LindsayYoung** [comment]
Yea, using the code hi-lighting for list was a bit of a workaround for formatting, if we could just get lists going in the documentation. That would be better, though our fork of Swagger is behind, we might want to tackle that too  : /

https://github.com/18F/openFEC/issues/1725
